spec = "prismpm/dependencies/1"

[[dependency]]
id = "lean4-prod"
lean_version = "4.32.1"
revision = "8bbafdc964af65d0e60cf027336822383ec76ba7"
source = "vendored"

[[dependency.artifact]]
kind = "file"
path = "vendor/lean4-prod/lean.tar"
sha256 = "069093cc7ccf3b19b5f2b7bf0aa75404b1c64b35767d6780a8aa01124a6c6b5e"

[[dependency.artifact]]
kind = "tree-manifest"
path = "vendor/lean4-prod/rust/MANIFEST.sha256"
sha256 = "ae5db76d4c2cb313deee526dcfa20b442cf5eba1f5c7137a1119ada3525fbe2f"
tree_root = "vendor/lean4-prod/rust"

[[dependency.artifact]]
kind = "file"
path = "vendor/lean4-prod/crates/prod-alloc-counter-0.1.0.crate"
sha256 = "3072374800280030ab1f03db059676f93d7f3d62df431895e32fe8c9eae8229e"

[[dependency.artifact]]
kind = "file"
path = "vendor/lean4-prod/crates/prod-codegen-0.1.0.crate"
sha256 = "6692e65c6aa5b969a74eecca16b8876b132cf1ff1a5b03fe7f0cd0cdac14bf53"

[[dependency.artifact]]
kind = "file"
path = "vendor/lean4-prod/crates/prod-ir-0.1.0.crate"
sha256 = "1877337169542a1d428b16cd30cce76b39accc9c17f28240a4439c61e22316b7"

[[dependency]]
id = "lexlean"
version = "0.3.0"
revision = "c40df5aa5308b396ada87378aed3f4b62ca0adc9"
source = "vendored"

[[dependency.artifact]]
kind = "tree-manifest"
path = "vendor/lexlean/MANIFEST.sha256"
sha256 = "444c60791fae7089fa823412ab4061eda4ed6d55321de865a52c76e3d0bed04e"
tree_root = "vendor/lexlean"

[[dependency.artifact]]
kind = "file"
path = "vendor/lexlean/lexlean-0.3.0.crate"
sha256 = "0f54652e454531dbee43a773511d90743e529ad1c712cda06706ce9532279f08"

[[dependency]]
id = "hologram-live"
version = "1.0.0"
revision = "d8208266d8abdc2445b7bbc0cef412a566adfaf1"
source = "vendored"

[[dependency.artifact]]
kind = "file"
path = "vendor/hologram-live.tar"
sha256 = "caf5c34ef2b21d58c1aa12acf81cb13ace1adaffb3c69a641f54f490ed61cf66"

[[dependency]]
id = "uor-hologram"
revision = "2bda6a9a9476872dade705bd61ece4209607f6da"
source = "git"
