// Synthetic linkage fixtures only; these tests do not claim a Lean kernel run.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {captureKernelProvenance} from './kernel-provenance.mjs';

const modules = ['Fixture', 'Foundation.Bytes', 'Foundation.Codec',
  'Foundation.Codec.Cbor.V1.Primitive', 'Foundation.View.Browser.V1.Model',
  'Foundation.View.Browser.V1.Wire'];
const sha = value => createHash('sha256').update(value).digest('hex');
const json = value => JSON.stringify(value, function(_key, child) {
  if (child && !Array.isArray(child) && typeof child === 'object')
    return Object.fromEntries(Object.entries(child).sort(([a], [b]) => a.localeCompare(b, 'en')));
  return child;
});
const file = value => Buffer.from(json(value) + '\n');
function frame(domain, label, payload, continuation = []) {
  const chunks = [Buffer.from(domain + '\0')];
  for (const [key, value] of [[label, payload], ...continuation]) {
    const keyLength = Buffer.alloc(4), valueLength = Buffer.alloc(8);
    keyLength.writeUInt32BE(Buffer.byteLength(key)); valueLength.writeBigUInt64BE(BigInt(value.length));
    chunks.push(keyLength, Buffer.from(key), valueLength, value);
  }
  return sha(Buffer.concat(chunks));
}
function fixture() {
  const sources = new Map(modules.map(name => [name, Buffer.from('synthetic source ' + name)]));
  const generated = new Map(modules.map(name => [name, Buffer.from('synthetic generated bytes ' + name)]));
  const source_id = sha('source'), semantic_id = sha('semantic');
  const build_id = frame('lexlean-build-v1', 'source-id', Buffer.from(source_id, 'hex'),
    [['semantic-id', Buffer.from(semantic_id, 'hex')]]);
  const row = (kind, path, value) => ({kind, path, byte_length: value.length, sha256: sha(value)});
  const manifest = {spec: 'lexlean/build-manifest/1', source_id, semantic_id, build_id,
    selection: modules, modules: modules.map(name => ({module: name, lean_module: 'PrismPM.' + name,
      source_path: 'src/' + name.replaceAll('.', '/') + '.lex.tex'})),
    inputs: [...sources].map(([name, value]) => row('source', 'src/' + name.replaceAll('.', '/') + '.lex.tex', value)),
    outputs: [...generated].map(([name, value]) => row('lean', 'modules/PrismPM/' + name.replaceAll('.', '/') + '.lean', value))};
  const verified = {source_id, semantic_id, build_id, attestation_id: '', root: '/private/verified', modules};
  const attestation = {spec: 'lexlean/attestation/1', status: 'verified', source_id, semantic_id, build_id};
  const input = {verified, sources, generated, manifestBytes: null, attestationBytes: null};
  function bind() {
    input.manifestBytes = file(manifest);
    attestation.build_manifest = {byte_length: input.manifestBytes.length, sha256: sha(input.manifestBytes)};
    delete attestation.attestation_id;
    attestation.attestation_id = frame('lexlean-attestation-v1', 'attestation-body', Buffer.from(json(attestation)));
    verified.attestation_id = attestation.attestation_id;
    input.attestationBytes = file(attestation);
    return input;
  }
  return {input: bind(), bind, manifest, attestation};
}

test('exact six-module byte linkage captures immutable records and defensive generated bytes', () => {
  const {input} = fixture(), captured = captureKernelProvenance(modules, input);
  captured.verify({...input, staged: new Map(input.generated)});
  assert.throws(() => {captured.evidence.verified.source_id = '0'.repeat(64);}, TypeError);
  assert.throws(() => {captured.snapshot.manifest.outputs[0].sha256 = '0'.repeat(64);}, TypeError);
  assert.throws(() => {captured.evidence.generated[0].path = 'other';}, TypeError);
  const value = captured.generatedBytes('Fixture'); value[0] ^= 1;
  assert.deepEqual(captured.generatedBytes('Fixture'), input.generated.get('Fixture'));
  assert.throws(() => captured.generatedBytes('Other'), /captured generated module/);
});

test('changed source or generated Lean cannot inherit the authenticated kernel manifest', () => {
  for (const kind of ['sources', 'generated']) for (const name of modules) {
    const {input} = fixture();
    input[kind].set(name, Buffer.concat([input[kind].get(name), Buffer.from('changed')]));
    assert.throws(() => captureKernelProvenance(modules, input), /byte length|byte digest/);
  }
  const {input} = fixture(), original = input.generated.get('Fixture');
  input.generated.set('Fixture', Buffer.from(original)); input.generated.get('Fixture')[0] ^= 1;
  assert.throws(() => captureKernelProvenance(modules, input), /byte digest/);
});

test('missing, extra, duplicate, relabeled or aliased inventories are rejected', () => {
  for (const field of ['inputs', 'outputs']) for (const kind of ['missing', 'duplicate', 'extra', 'path', 'kind', 'row-field']) {
    const f = fixture(), rows = f.manifest[field];
    if (kind === 'missing') rows.pop();
    if (kind === 'duplicate') rows.push({...rows[0]});
    if (kind === 'extra') rows.push({...rows[0], path: 'unexpected.lean'});
    if (kind === 'path') rows[0].path = '../escape';
    if (kind === 'kind') rows[0].kind = 'other';
    if (kind === 'row-field') rows[0].substitute = true;
    assert.throws(() => captureKernelProvenance(modules, f.bind()), /inventory|kind|descriptor/);
  }
  for (const field of ['sources', 'generated']) for (const operation of ['missing', 'extra', 'order']) {
    const {input} = fixture();
    if (operation === 'missing') input[field].delete('Fixture');
    if (operation === 'extra') input[field].set('Other', Buffer.from('x'));
    if (operation === 'order') input[field] = new Map([...input[field]].reverse());
    assert.throws(() => captureKernelProvenance(modules, input), /module inventory/);
  }
});

test('driver, manifest, attestation and build content identities cannot be substituted', () => {
  for (const key of ['source_id', 'semantic_id', 'build_id', 'attestation_id']) {
    const {input} = fixture(); input.verified[key] = '0'.repeat(64);
    assert.throws(() => captureKernelProvenance(modules, input), /driver/);
  }
  for (const object of ['manifest', 'attestation']) for (const key of ['source_id', 'semantic_id', 'build_id']) {
    const f = fixture(); f[object][key] = '0'.repeat(64);
    assert.throws(() => captureKernelProvenance(modules, f.bind()), /driver/);
  }
  const f = fixture();
  for (const object of [f.input.verified, f.manifest, f.attestation]) object.build_id = '0'.repeat(64);
  assert.throws(() => captureKernelProvenance(modules, f.bind()), /actual build content ID/);
  const g = fixture(); g.attestation.status = 'failed'; g.bind();
  assert.throws(() => captureKernelProvenance(modules, g.input), /verified/);
});

test('manifest bytes, exact length and attestation body bind before generated bytes are trusted', () => {
  for (const field of ['sha256', 'byte_length']) {
    const f = fixture(); f.attestation.build_manifest[field] = field === 'sha256' ? '0'.repeat(64) : 0;
    delete f.attestation.attestation_id;
    f.attestation.attestation_id = frame('lexlean-attestation-v1', 'attestation-body', Buffer.from(json(f.attestation)));
    f.input.verified.attestation_id = f.attestation.attestation_id;
    f.input.attestationBytes = file(f.attestation);
    assert.throws(() => captureKernelProvenance(modules, f.input), /attested manifest/);
  }
  const f = fixture(); f.attestation.source_id = '0'.repeat(64); f.input.attestationBytes = file(f.attestation);
  assert.throws(() => captureKernelProvenance(modules, f.input), /attestation\/driver|attestation content ID/);
  const g = fixture(); g.attestation.extra = true; g.input.attestationBytes = file(g.attestation);
  assert.throws(() => captureKernelProvenance(modules, g.input), /actual attestation content ID/);
  const h = fixture(); h.manifest.outputs[0].sha256 = '0'.repeat(64); h.input.manifestBytes = file(h.manifest);
  assert.throws(() => captureKernelProvenance(modules, h.input), /attested manifest digest/);
});

test('canonical files reject duplicate fields, noncanonical bytes and invalid UTF-8', () => {
  for (const field of ['manifestBytes', 'attestationBytes']) for (const operation of ['duplicate', 'space', 'utf8']) {
    const {input} = fixture(), text = input[field].toString();
    input[field] = operation === 'duplicate' ? Buffer.from(text.replace('{', '{"spec":"duplicate",'))
      : operation === 'space' ? Buffer.from(' ' + text) : Buffer.concat([Buffer.from([0xff]), input[field]]);
    assert.throws(() => captureKernelProvenance(modules, input), /canonical file bytes|encoded data/);
  }
});

test('post-capture checks refuse original/staged/receipt/driver replacement, even consistently rehashed inputs', () => {
  for (const field of ['sources', 'generated', 'staged']) {
    const {input} = fixture(), owner = captureKernelProvenance(modules, input);
    input.staged = new Map(input.generated);
    input[field].set('Fixture', Buffer.from('replaced'));
    assert.throws(() => owner.verify(input), /immutable.*(source|generated Lean)/);
  }
  for (const field of ['source_id', 'attestation_id', 'root']) {
    const {input} = fixture(), owner = captureKernelProvenance(modules, input);
    input.verified[field] = 'replacement';
    assert.throws(() => owner.verify(input), /immutable actual driver/);
  }
  for (const field of ['manifestBytes', 'attestationBytes']) {
    const {input} = fixture(), owner = captureKernelProvenance(modules, input);
    input[field][input[field].length - 1] ^= 1;
    assert.throws(() => owner.verify(input), /immutable (authenticated manifest|kernel attestation)/);
  }
  const f = fixture(), owner = captureKernelProvenance(modules, f.input);
  f.input.generated.set('Fixture', Buffer.from('changed'));
  f.manifest.outputs[0].sha256 = sha(f.input.generated.get('Fixture'));
  f.manifest.outputs[0].byte_length = f.input.generated.get('Fixture').length;
  assert.throws(() => owner.verify(f.bind()), /immutable actual driver|immutable authenticated manifest/);
});
