// Execute captured generated bytes; no field/point arithmetic exists in this bridge.
import assert from 'node:assert/strict';
import {withBrowser} from '../../sdk/browser/browser-test-server.mjs';
import {requireGeneratedWasm} from '../browser-view/generated-wasm.mjs';
import {corpus,CORPUS_CASES} from './corpus.mjs';

export function verifyBrowserTranscript(result,engine){
  assert.equal(result.engine,engine);assert.equal(result.calls.length,CORPUS_CASES);
  const expected=corpus();
  for(let i=0;i<expected.length;i++){
    assert.deepEqual(result.calls[i],{id:expected[i].id,request:expected[i].request.toString('hex'),
      response:expected[i].response.toString('hex'),repeats:2},'exact generated browser call '+expected[i].id);
  }
  assert.ok(result.maximumBytes>0&&result.maximumBytes<=1073741824);
  assert.equal(result.imports,0);assert.equal(result.allocatorMaximum,1024);
  assert.equal(result.allocatorFirstOverRejected,true);
}
export async function browserFixture(build,engine){
  build.unchanged();
  const artifact=requireGeneratedWasm(build.wasmOwners.p256),rows=corpus().map(row=>({id:row.id,
    request:row.request.toString('hex')}));
  return artifact.runAsync(async bytes=>withBrowser(async({browser,baseURL})=>{
    const page=await browser.newPage();
    try{
      await page.goto(baseURL);
      const result=await page.evaluate(async({artifact,rows})=>{
        const module=new WebAssembly.Module(Uint8Array.from(artifact));
        const hex=value=>Array.from(value,byte=>byte.toString(16).padStart(2,'0')).join('');
        const decode=value=>Uint8Array.from(value.match(/.{2}/g)??[],byte=>parseInt(byte,16));
        const calls=[];let maximumBytes=0;
        for(const row of rows){
          let response=null;
          for(let repeat=0;repeat<2;repeat++){
            const instance=new WebAssembly.Instance(module,{}),request=decode(row.request);
            const memory=instance.exports.memory,pointer=instance.exports.holo_alloc(request.length)>>>0;
            if(pointer+request.length>memory.buffer.byteLength)throw Error('input allocator bounds');
            new Uint8Array(memory.buffer,pointer,request.length).set(request);
            const output=instance.exports.holo_run(pointer,request.length);
            if(typeof output!=='bigint')throw Error('actual binary guest result required');
            const packed=BigInt.asUintN(64,output),offset=Number(packed>>32n),length=Number(packed&0xffffffffn);
            if(length>512||offset+length>memory.buffer.byteLength)throw Error('output allocator bounds');
            const actual=hex(new Uint8Array(memory.buffer,offset,length));
            if(response!==null&&response!==actual)throw Error('nondeterministic actual guest');
            response=actual;maximumBytes=Math.max(maximumBytes,memory.buffer.byteLength);
          }
          calls.push({id:row.id,request:row.request,response,repeats:2});
        }
        const maximumInstance=new WebAssembly.Instance(module,{});
        const maximum=maximumInstance.exports.holo_alloc(1024)>>>0;
        if(maximum+1024>maximumInstance.exports.memory.buffer.byteLength)throw Error('maximum allocation missing');
        let allocatorFirstOverRejected=false;
        try{maximumInstance.exports.holo_alloc(1025);}catch(error){if(!(error instanceof WebAssembly.RuntimeError))throw error;allocatorFirstOverRejected=true;}
        return{calls,maximumBytes,imports:WebAssembly.Module.imports(module).length,allocatorMaximum:1024,allocatorFirstOverRejected};
      },{artifact:Array.from(bytes),rows});
      result.engine=engine;result.version=browser.version();
      verifyBrowserTranscript(result,engine);build.unchanged();return result;
    }finally{await page.close();}
  },{engine}));
}
