// Oracle harness only: execute the actual generated byte entry without imports.
import assert from 'node:assert/strict';
import {inspectEffectModule} from '../../sdk/browser/effects-module.mjs';

export function executeWasm(bytes, vectors) {
  const limits = inspectEffectModule(bytes, 16384), module = new WebAssembly.Module(bytes);
  assert.deepEqual(WebAssembly.Module.imports(module), []);
  assert.equal(limits.maximumPages, 16384);
  let maximumBytes = 0;
  for (const row of vectors) for (let repeat = 0; repeat < 2; repeat++) {
    const instance = new WebAssembly.Instance(module, {}), {memory, holo_alloc: allocate, holo_run: run} = instance.exports;
    const pointer = allocate(row.request.length) >>> 0;
    assert.ok(pointer + row.request.length <= memory.buffer.byteLength);
    new Uint8Array(memory.buffer, pointer, row.request.length).set(row.request);
    const result = run(pointer, row.request.length);
    assert.equal(typeof result, 'bigint');
    const packed = BigInt.asUintN(64, result), at = Number(packed >> 32n), length = Number(packed & 0xffffffffn);
    assert.ok(length <= 512 && at + length <= memory.buffer.byteLength);
    assert.deepEqual(new Uint8Array(memory.buffer, at, length).slice(), new Uint8Array(row.response), row.id);
    maximumBytes = Math.max(maximumBytes, memory.buffer.byteLength);
    assert.ok(maximumBytes <= 1073741824);
  }
  const invalid = new WebAssembly.Instance(module, {});
  const maximum = invalid.exports.holo_alloc(1024) >>> 0;
  assert.ok(maximum + 1024 <= invalid.exports.memory.buffer.byteLength);
  assert.throws(() => invalid.exports.holo_alloc(1025), WebAssembly.RuntimeError);
  assert.throws(() => invalid.exports.memory.grow(16384), RangeError);
  return {maximumBytes, declaredPages: limits.maximumPages};
}

export const tsv = rows => rows.map(row => row.id + '\t' + Buffer.from(row.request).toString('hex')
  + '\t' + Buffer.from(row.response).toString('hex') + '\n').join('');
