//! Generation of documentation derived from model/*.toml registers.

use crate::Model;
use core::fmt::Write as _;

/// Path where CONFORMANCE.md is committed.
pub const CONFORMANCE_PATH: &str = "CONFORMANCE.md";

/// Path where ERRORS.md is committed.
pub const ERRORS_PATH: &str = "ERRORS.md";

/// Path where the public schema, media-type, and command references are committed.
pub const CONTRACTS_PATH: &str = "CONTRACTS.md";

/// Render the normative SPEC.md conformance appendix from the ID register.
pub fn render_spec_appendix(model: &Model) -> String {
    let mut out = String::from("## Appendix A. Conformance ID Registry\n\n");
    out.push_str("Every row below is normative, has the honesty level registered in `model/ids.toml`, and is generated from that register.\n\n");
    out.push_str("| ID | Suite | Normative statement | Primary specification |\n");
    out.push_str("|---|---|---|---|\n");
    for row in &model.ids.id {
        let primary = match row.suite.as_str() {
            "repository" => "§1",
            "facets" => "§2",
            "holo" => "§3",
            "controller" => "§4",
            "stdlib" => "§5",
            "artifacts" => "§6",
            "execution" => "§7",
            "verification" => "§8",
            "security" => "§9",
            "authorities" => "§10",
            "system" => "§11",
            "sdk" => "§12",
            "oci" => "§13",
            "lifecycle" => "§14",
            "deployment" => "§15",
            "operations" | "supply-chain" => "§16",
            "template-ci" => "§17",
            _ => "§1",
        };
        let statement = row.statement.replace('\n', " ").replace('|', "\\|");
        let _ = writeln!(
            out,
            "| `{}` | `{}` | {} | {} |",
            row.id,
            row.suite,
            statement.trim(),
            primary
        );
    }
    out
}

/// Render CONFORMANCE.md from model registers.
pub fn render_conformance(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "<!-- @generated by `cargo xtask validate-model --write` from model/ids.toml. -->"
    );
    let _ = writeln!(
        w,
        "<!-- Do not edit. R1: the model is the single source. -->"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "# CONFORMANCE");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "The conformance ID register (SPEC.md). Every ID has exactly one scenario"
    );
    let _ = writeln!(
        w,
        "in `features/suites/` and exactly one test named `conformance_<id>`."
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "The three honesty levels:");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Level | Meaning |");
    let _ = writeln!(w, "| --- | --- |");
    let _ = writeln!(
        w,
        "| `some-true` | A fact reproduced from an authority. **Not established here.** |"
    );
    let _ = writeln!(
        w,
        "| `build` | Constructed here and validated against its oracle. Evidence, not a proof. |"
    );
    let _ = writeln!(w, "| `open` | Measured and reported. **Never asserted.** |");
    let _ = writeln!(w);

    let mut suites: Vec<&str> = model.ids.id.iter().map(|r| r.suite.as_str()).collect();
    suites.sort_unstable();
    suites.dedup();

    for suite in suites {
        let rows: Vec<_> = model.ids.id.iter().filter(|r| r.suite == suite).collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(w);
        let _ = writeln!(w, "## {suite}");
        let _ = writeln!(w);
        let _ = writeln!(w, "| ID | Level | Statement |");
        let _ = writeln!(w, "| --- | --- | --- |");
        for r in rows {
            let statement = r.statement.replace('\n', " ").replace('|', "\\|");
            let _ = writeln!(
                w,
                "| `{}` | `{}` | {} |",
                r.id,
                r.level.as_str(),
                statement.trim()
            );
        }
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Cited authorities");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "| Authority | Edition | Immutable source | Acquired SHA-256 | Evidence here |"
    );
    let _ = writeln!(w, "| --- | --- | --- | --- | --- |");
    for a in &model.authorities.authority {
        let citation = a.immutable_url.replace('\n', " ").replace('|', "\\|");
        let realized = if a.realized_by.is_empty() {
            "--".to_string()
        } else {
            a.realized_by
                .iter()
                .map(|i| format!("`{i}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            w,
            "| `{}` | `{}` | {} | `{}` | {realized} |",
            a.id,
            a.edition,
            citation.trim(),
            a.acquired_sha256
        );
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Claims that are not conformance IDs");
    let _ = writeln!(w);
    let _ = writeln!(w, "| ID | Level | Claim |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for c in &model.ledger.claim {
        let statement = c.statement.replace('\n', " ").replace('|', "\\|");
        let _ = writeln!(
            w,
            "| `{}` | `{}` | {} |",
            c.id,
            c.level.as_str(),
            statement.trim()
        );
    }

    out
}

/// Render ERRORS.md from model registers.
pub fn render_errors(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "<!-- @generated by `cargo xtask validate-model --write` from model/errors.toml and model/browser-diagnostics.toml. -->"
    );
    let _ = writeln!(
        w,
        "<!-- Do not edit. R1: the model is the single source. -->"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "# ERRORS");
    let _ = writeln!(w);
    let _ = writeln!(w, "The closed CLI diagnostic registry uses PP codes; the browser journal has a separate typed namespace below.");
    for row in &model.errors.error {
        let _ = writeln!(w);
        let _ = writeln!(w, "## `{}` --- {}", row.code, row.title);
        let _ = writeln!(w);
        let _ = writeln!(w, "{}", row.statement);
        let _ = writeln!(w);
        let _ = writeln!(w, "Class: `{}`. Exit code: {}.", row.class, row.exit);
    }
    let _ = writeln!(w, "\n## Browser journal diagnostics\n");
    let _ = writeln!(w, "JournalAdapterError codes are registered in model/browser-diagnostics.toml and owned by DK-12. Known propagated BrowserEffectError codes retain the SPEC section 12.1 namespace. Private defensive-boundary tests do not claim those invalid internal values are public journeys.\n");
    let _ = writeln!(w, "| Code | Meaning |\n|---|---|");
    for row in &model.browser_diagnostics.error {
        let _ = writeln!(w, "| `{}` | {} |", row.code, row.statement);
    }
    for adapter in &model.browser_adapter_diagnostics.adapter {
        let _ = writeln!(w, "\n## {} diagnostics\n", adapter.error_class);
        let _ = writeln!(w, "Registered in model/browser-adapter-diagnostics.toml; owned by {}. JournalAdapterError and BrowserEffectError remain separate propagated namespaces. Negative-only guard tests are not public journeys.\n", adapter.capability);
        let _ = writeln!(w, "| Code | Meaning |\n|---|---|");
        for row in &adapter.error {
            let _ = writeln!(w, "| `{}` | {} |", row.code, row.statement);
        }
        let _ = writeln!(
            w,
            "\nThe `{}` detail is the exact generated byte:\n",
            adapter.rejection_error
        );
        let _ = writeln!(w, "| Byte | Modeled rejection |\n|---|---|");
        for row in &adapter.rejection {
            let _ = writeln!(w, "| {} | `{}` |", row.byte, row.name);
        }
    }
    let view = &model.browser_view_diagnostics;
    let _ = writeln!(w, "\n## ViewHostError diagnostics\n");
    let _ = writeln!(w, "Registered separately in model/browser-view-diagnostics.toml; owned by DK-16. Private defensive guards are distinct from public journeys. Journal and Command/Query namespaces are unchanged.\n");
    let _ = writeln!(w, "| Code | Meaning |\n|---|---|");
    for row in &view.error {
        let _ = writeln!(w, "| `{}` | {} |", row.code, row.statement);
    }
    let _ = writeln!(
        w,
        "\nThe model-rejected detail is the exact generated byte:\n"
    );
    let _ = writeln!(w, "| Byte | Modeled rejection |\n|---|---|");
    for row in &view.rejection {
        let _ = writeln!(w, "| {} | `{}` |", row.byte, row.name);
    }
    out
}

/// Render the stable machine contracts from the typed registers.
pub fn render_contracts(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "<!-- @generated by `cargo xtask validate-model --write` from model/contracts.toml and model/commands.toml. -->"
    );
    let _ = writeln!(
        w,
        "<!-- Do not edit. R1: the model is the single source. -->"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "# PrismPM machine contracts");
    let _ = writeln!(w);
    let _ = writeln!(w, "All JSON content uses UTF-8, sorted object keys, shortest canonical integers, no insignificant whitespace, and SHA-256 over the canonical bytes. CLI JSON adds one framing newline after those bytes.");
    let _ = writeln!(w);
    let _ = writeln!(w, "## Data contracts");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "| Schema | JSON Schema | Media type | Limits | Compatibility |"
    );
    let _ = writeln!(w, "| --- | --- | --- | --- | --- |");
    for row in &model.contracts.contract {
        let _ = writeln!(
            w,
            "| `{}` | `{}` | `{}` | {} bytes / {} items | `{}`; `{}` |",
            row.schema,
            row.path,
            row.media_type,
            row.maximum_bytes,
            row.maximum_items,
            row.extension_policy,
            row.compatibility
        );
    }
    let _ = writeln!(w);
    let _ = writeln!(w, "## Command state and mutation boundaries");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "| Command | Mutation boundary | Digest required | Result schema |"
    );
    let _ = writeln!(w, "| --- | --- | --- | --- |");
    for row in &model.commands.command {
        let _ = writeln!(
            w,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.name, row.mutates, row.requires_digest, row.result_schema
        );
    }
    out
}
