//! Generation of documentation derived from model/*.toml registers.

use core::fmt::Write as _;
use crate::Model;

/// Path where CONFORMANCE.md is committed.
pub const CONFORMANCE_PATH: &str = "CONFORMANCE.md";

/// Path where ERRORS.md is committed.
pub const ERRORS_PATH: &str = "ERRORS.md";

/// Render CONFORMANCE.md from model registers.
pub fn render_conformance(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "<!-- @generated by `cargo xtask validate-model --write` from model/ids.toml. -->");
    let _ = writeln!(w, "<!-- Do not edit. R1: the model is the single source. -->");
    let _ = writeln!(w);
    let _ = writeln!(w, "# CONFORMANCE");
    let _ = writeln!(w);
    let _ = writeln!(w, "The conformance ID register (SPEC.md). Every ID has exactly one scenario");
    let _ = writeln!(w, "in `features/suites/` and exactly one test named `conformance_<id>`.");
    let _ = writeln!(w);
    let _ = writeln!(w, "The three honesty levels:");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Level | Meaning |");
    let _ = writeln!(w, "| --- | --- |");
    let _ = writeln!(w, "| `some-true` | A fact reproduced from an authority. **Not established here.** |");
    let _ = writeln!(w, "| `build` | Constructed here and validated against its oracle. Evidence, not a proof. |");
    let _ = writeln!(w, "| `open` | Measured and reported. **Never asserted.** |");
    let _ = writeln!(w);

    let mut suites: Vec<&str> = model.ids.id.iter().map(|r| r.suite.as_str()).collect();
    suites.sort_unstable();
    suites.dedup();

    for suite in suites {
        let rows: Vec<_> = model.ids.id.iter().filter(|r| r.suite == suite).collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(w);
        let _ = writeln!(w, "## {suite}");
        let _ = writeln!(w);
        let _ = writeln!(w, "| ID | Level | Statement |");
        let _ = writeln!(w, "| --- | --- | --- |");
        for r in rows {
            let statement = r.statement.replace('\n', " ").replace('|', "\\|");
            let _ = writeln!(w, "| `{}` | `{}` | {} |", r.id, r.level.as_str(), statement.trim());
        }
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Cited authorities");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Authority | Citation | Evidence here |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for a in &model.authorities.authority {
        let citation = a.citation.replace('\n', " ").replace('|', "\\|");
        let realized = if a.realized_by.is_empty() {
            "--".to_string()
        } else {
            a.realized_by.iter().map(|i| format!("`{i}`")).collect::<Vec<_>>().join(", ")
        };
        let _ = writeln!(w, "| `{}` | {} | {realized} |", a.id, citation.trim());
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Claims that are not conformance IDs");
    let _ = writeln!(w);
    let _ = writeln!(w, "| ID | Level | Claim |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for c in &model.ledger.claim {
        let statement = c.statement.replace('\n', " ").replace('|', "\\|");
        let _ = writeln!(w, "| `{}` | `{}` | {} |", c.id, c.level.as_str(), statement.trim());
    }

    out
}

/// Render ERRORS.md from model registers.
pub fn render_errors(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "<!-- @generated by `cargo xtask validate-model --write` from model/errors.toml. -->");
    let _ = writeln!(w, "<!-- Do not edit. R1: the model is the single source. -->");
    let _ = writeln!(w);
    let _ = writeln!(w, "# ERRORS");
    let _ = writeln!(w);
    let _ = writeln!(w, "The closed public diagnostic registry. Every user-visible failure carries exactly one of these codes.");
    for row in &model.errors.error {
        let _ = writeln!(w);
        let _ = writeln!(w, "## `{}` --- {}", row.code, row.title);
        let _ = writeln!(w);
        let _ = writeln!(w, "{}", row.statement);
        let _ = writeln!(w);
        let _ = writeln!(w, "Class: `{}`. Exit code: {}.", row.class, row.exit);
    }
    out
}

